Repository MakeContributions/markdown-dungeon, pull requests merged in 2020-08, with the labels that each got.

#4 add new option and linked to new floor
  english/normal-dungeon/0/0.md
  english/normal-dungeon/3/1-1A.md
  english/normal-dungeon/3/1.md
Labels: beginner

#9 Added intro page
  english/normal-dungeon/begin-journey.md
  start-new-game.md
Labels: beginner

#11 added book rooms, corrected dungeon spelling
  .gitignore
  english/normal-dungeon/0/0-1A.md
  english/normal-dungeon/0/0-1B.md
  english/normal-dungeon/0/1-1A.md
  english/normal-dungeon/0/1-1B.md
  english/normal-dungeon/0/1-1BA.md
  english/normal-dungeon/0/1-1BB.md
Labels: beginner

#18 Feature/Static page
  .env.example
  .gitignore
  README.md
  english/normal-dungeon/0/1-1A.md
  gatsby-browser.js
  gatsby-config.js
  gatsby-node.js
  package.json
  src/components/layout.jsx
  src/pages/404.jsx
  src/pages/index.jsx
  src/templates/blog-post.jsx
  src/utils/typography.js
  yarn.lock
Labels: enhancement, good first issue

#19 Docs/change license CC0 to MIT
  LICENSE
  README.md
  package.json
Labels: documentation

#8 Corrected the rooms
  english/normal-dungeon/0/0-1A.md
  english/normal-dungeon/0/0-1B.md
  english/normal-dungeon/0/0.md
  english/normal-dungeon/1/3-2.md
  english/normal-dungeon/1/3.md
Labels: beginner

#21 Expand Floor 2 in english/normal-dungeon
  english/normal-dungeon/2/1-A.md
  english/normal-dungeon/2/1.md
  english/normal-dungeon/2/2.md
  english/normal-dungeon/2/3-A.md
  english/normal-dungeon/2/3-B.md
  english/normal-dungeon/2/3-C.md
  english/normal-dungeon/2/3.md
Labels: beginner, enhancement

#24 docs: update installation section
  README.md
Labels: documentation

#27 Docs/common ending
  english/normal-dungeon/3/2.md
  english/normal-dungeon/3/3.md
  english/normal-dungeon/4/0.md
Labels: beginner, documentation, enhancement
