Repository MakeContributions/markdown-dungeon, pull requests merged in 2020-12, with the labels that each got.

#110 Add Covid-19 Dungeon (WIP)
  english/covid-19/0/0-B.md
  english/covid-19/0/0-BB.md
  english/covid-19/0/0-C.md
  english/covid-19/0/0-CA.md
  english/covid-19/0/0-CC.md
  english/covid-19/0/0-D.md
  english/covid-19/0/0-DA.md
  english/covid-19/0/0-DB.md
  english/covid-19/0/0-DD.md
  english/covid-19/0/0.md
  english/covid-19/1/1-A.md
  english/covid-19/1/1-B.md
  english/covid-19/1/1-C.md
  english/covid-19/1/1-CB.md
  english/covid-19/1/1-D.md
  english/covid-19/1/1.md
  english/covid-19/2/2-A.md
  english/covid-19/2/2.md
  english/covid-19/3/3.md
  english/covid-19/WIP.md
  english/covid-19/begin-journey.md
  start-new-game.md
Labels: good first issue, help wanted

#114 COVID-19 dungeon: Update WIP.md
  english/covid-19/WIP.md
Labels: documentation

#124 spell-check and re-word beginning of covid-19 dungeon for readability
  english/covid-19/0/0-D.md
  english/covid-19/0/0-DB.md
  english/covid-19/0/0.md
  english/covid-19/3/3-AA.md
  english/covid-19/3/3.md
Labels: beginner, documentation, enhancement

#125 More files translated to portuguese
  portuguese/normal-dugeon/1/1-1.md
  portuguese/normal-dugeon/1/1-1A.md
  portuguese/normal-dugeon/1/1.md
  portuguese/normal-dugeon/1/2-1A.md
  portuguese/normal-dugeon/1/2-1B.md
  portuguese/normal-dugeon/1/2-1C.md
Labels: beginner, documentation, enhancement, good first issue
