Repository MakeContributions/markdown-dungeon, pull requests merged in 2021-10, with the labels that each got.

#198 chore(sci-fi): add more room and floors
  english/sci-fi-dungeon/0/0.md
  english/sci-fi-dungeon/1/1-A.md
  english/sci-fi-dungeon/1/1-A1.md
  english/sci-fi-dungeon/1/1-A2.md
  english/sci-fi-dungeon/1/1-B.md
  english/sci-fi-dungeon/1/1-B1.md
  english/sci-fi-dungeon/WIP.md
  english/sci-fi-dungeon/begin-journey.md
Labels: enhancement, beginner, hacktoberfest-accepted

#199 chore(sci-fi): add rooms to first floor
  english/sci-fi-dungeon/1/1-A1.md
  english/sci-fi-dungeon/1/1-A2.md
  english/sci-fi-dungeon/1/1-A2X.md
  english/sci-fi-dungeon/1/1-B.md
  english/sci-fi-dungeon/1/1-B1.md
  english/sci-fi-dungeon/1/1-B1A.md
  english/sci-fi-dungeon/1/1-B1B.md
Labels: documentation, enhancement, hacktoberfest-accepted

#200 docs: translate readme to Chinese
  translations/README.ch.md
  translations/README.md
Labels: enhancement, hacktoberfest-accepted

#201 docs(readme): update title and information
  README.md
  translations/README.ch.md
Labels: enhancement, hacktoberfest-accepted, hacktoberfest
