Repository MakeContributions/markdown-dungeon, pull requests merged in 2021-09, with the labels that each got.

#190 chore(COVID-19): add new story
  english/covid-19/2/2-B.md
  english/covid-19/2/2-BA.md
  english/covid-19/2/2-BB.md
  english/covid-19/2/2-BBC.md
  english/covid-19/2/2.md
Labels: enhancement, beginner, hacktoberfest-accepted

#194 docs: proofread the readme
  README.md
Labels: documentation

#193 chore(normal-dungeon): added sub-story
  english/normal-dungeon/0/0.md
  english/normal-dungeon/0/1-1D.md
  english/normal-dungeon/0/1-1DA.md
  english/normal-dungeon/0/1-1DB.md
  english/normal-dungeon/0/1-1DC.md
Labels: documentation, enhancement, hacktoberfest-accepted
