Repository MakeContributions/markdown-dungeon, pull requests merged in 2021-03, with the labels that each got.

#140 Correcting typos and translating content
  portuguese/normal-dugeon/0/0-1AAA.md
  portuguese/normal-dugeon/0/1-1B.md
  portuguese/normal-dugeon/0/1-1CA.md
  portuguese/normal-dugeon/0/1-1CB.md
  portuguese/normal-dugeon/1/2-1D.md
  portuguese/normal-dugeon/1/2.md
  portuguese/normal-dugeon/1/3-1.md
  portuguese/normal-dugeon/1/3-2.md
  portuguese/normal-dugeon/1/3-3.md
  portuguese/normal-dugeon/1/3-4.md
  portuguese/normal-dugeon/1/3.md
  portuguese/normal-dugeon/1/4.md
Labels: beginner, documentation, enhancement, good first issue

#142 Docs: Module 2 translated to PT-BR
  portuguese/normal-dugeon/2/1-A.md
  portuguese/normal-dugeon/2/1.md
  portuguese/normal-dugeon/2/2.md
  portuguese/normal-dugeon/2/3-A.md
  portuguese/normal-dugeon/2/3-B.md
  portuguese/normal-dugeon/2/3-C.md
  portuguese/normal-dugeon/2/3.md
Labels: documentation

#143 Fixed Typos in README.md
  README.md
Labels: beginner, documentation, enhancement

#141 [Feature] Beautify home page using material UI
  gatsby-config.js
  package.json
  src/components/card-grid.jsx
  src/components/copyright.jsx
  src/components/hide-appbar.jsx
  src/data/dungeon-info.json
  src/pages/index.jsx
  src/utils/styles.js
  static/images/covid-19.jpg
  static/images/dungeon.jpg
  static/images/great-wall.jpg
  yarn.lock
Labels: enhancement, hacktoberfest-accepted
