Repository MakeContributions/markdown-dungeon, pull requests merged in 2021-05, with the labels that each got.

#155 chore(covid): added two new rooms
  english/covid-19/0/0-BB.md
  english/covid-19/0/0-BBA.md
  english/covid-19/1/1-D.md
  english/covid-19/1/1-DB.md
Labels: documentation, enhancement, hacktoberfest-accepted

#156 chore(normal-dungeon): add spaces before emojis
  portuguese/normal-dungeon/0/0-1AA.md
  portuguese/normal-dungeon/0/0-1B.md
  portuguese/normal-dungeon/0/0.md
  portuguese/normal-dungeon/0/1-1A.md
  portuguese/normal-dungeon/0/1-1B.md
  portuguese/normal-dungeon/0/1-1BA.md
  portuguese/normal-dungeon/0/1-1BB.md
  portuguese/normal-dungeon/0/1-1CA.md
  portuguese/normal-dungeon/0/1-1CB.md
  portuguese/normal-dungeon/1/1-1.md
  portuguese/normal-dungeon/1/1.md
  portuguese/normal-dungeon/1/2-1A.md
  portuguese/normal-dungeon/1/2-1B.md
  portuguese/normal-dungeon/1/3-1.md
  portuguese/normal-dungeon/1/3.md
  portuguese/normal-dungeon/1/4.md
  portuguese/normal-dungeon/begin-journey.md
Labels: beginner, hacktoberfest-accepted

#157 chore(covid-19): added emojis on the rooms
  english/covid-19/0/0-BB.md
  english/covid-19/0/0-BBA.md
  english/covid-19/0/0-CA.md
  english/covid-19/0/0-CC.md
  english/covid-19/0/0-DA.md
  english/covid-19/0/0-DB.md
  english/covid-19/0/0-DD.md
  english/covid-19/1/1-CB.md
  english/covid-19/1/1-D.md
  english/covid-19/1/1-DB.md
  english/covid-19/2/2-A.md
  english/covid-19/2/2.md
  english/covid-19/3/3-A.md
  english/covid-19/3/3-AB.md
  english/covid-19/3/3-C.md
  english/covid-19/3/3.md
Labels: documentation, enhancement, hacktoberfest-accepted

#158 docs: added emojis to normal dungeon, floor 9
  english/normal-dungeon/9/0.md
  english/normal-dungeon/9/1.md
  english/normal-dungeon/9/2.md
  english/normal-dungeon/9/3-B.md
  english/normal-dungeon/9/3-C.md
  english/normal-dungeon/9/3-CA.md
  english/normal-dungeon/9/3-DA.md
  english/normal-dungeon/9/4-A.md
  english/normal-dungeon/9/4-B.md
  english/normal-dungeon/9/4.md
Labels: documentation, hacktoberfest-accepted
