Repository MakeContributions/markdown-dungeon, pull requests merged in 2021-07, with the labels that each got.

#167 chore(time-travel): add more options
  english/time-travel/0/4.md
  english/time-travel/0/5.md
  english/time-travel/0/6.md
Labels: beginner, documentation, enhancement, hacktoberfest-accepted

#169 chore(time-travel): added emojis, and fix the grammar
  english/time-travel/0/0.md
  english/time-travel/0/1.md
  english/time-travel/0/2.md
  english/time-travel/0/3.md
  english/time-travel/0/4.md
  english/time-travel/0/5.md
  english/time-travel/0/6.md
  english/time-travel/1/0.md
  english/time-travel/1/1.md
  english/time-travel/1/2.md
  english/time-travel/begin-journey.md
Labels: documentation, enhancement, hacktoberfest-accepted

#170 chore(covid-19): added a scenario to the serum
  english/covid-19/3/3-C.md
  english/covid-19/3/3-CA.md
Labels: beginner, enhancement, hacktoberfest-accepted

#172 chore: changed appBar color and font size
  src/components/hide-appbar.jsx
  src/utils/styles.js
Labels: documentation, enhancement, hacktoberfest-accepted

#173 chore(covid-19): add a new room
  english/covid-19/3/3-CA.md
  english/covid-19/3/3-CAA.md
Labels: beginner, enhancement, hacktoberfest-accepted

#177 docs: fix typo
  english/covid-19/3/3-CA.md
Labels: beginner, documentation, enhancement, hacktoberfest-accepted

#178 docs: grammar improvments
  english/normal-dungeon/6/1.md
  english/normal-dungeon/6/2.md
  english/normal-dungeon/6/3.md
  english/normal-dungeon/6/4.md
Labels: beginner, documentation, enhancement, hacktoberfest-accepted

#179 chore(great-wall): added new floor
  chinese/great-wall/0/3-1C.md
  chinese/great-wall/0/3-1D.md
  chinese/great-wall/0/3.md
Labels: enhancement, hacktoberfest-accepted
