Repository MakeContributions/markdown-dungeon, pull requests merged in 2021-06, with the labels that each got.

#160 chore(Covid-19): added a vaccination floor
  english/covid-19/4/4.md
Labels: documentation, enhancement, hacktoberfest-accepted

#161 chore: added emojis, fixed typos and grammatical errors and spaced text out
  english/normal-dungeon/4/1-A.md
  english/normal-dungeon/4/1.md
  english/normal-dungeon/4/2.md
  english/normal-dungeon/4/3-A.md
  english/normal-dungeon/4/3-B.md
  english/normal-dungeon/4/3-C.md
  english/normal-dungeon/4/3.md
  english/normal-dungeon/4/4.md
  english/normal-dungeon/5/1-A.md
  english/normal-dungeon/5/1-B.md
  english/normal-dungeon/5/1.md
  english/normal-dungeon/5/2.md
  english/normal-dungeon/5/3.md
  english/normal-dungeon/5/4.md
  english/normal-dungeon/5/5.md
Labels: documentation, enhancement, hacktoberfest-accepted

#165 chore: added time-travel dungeon
  .gitignore
  english/time-travel/0/0.md
  english/time-travel/0/1.md
  english/time-travel/0/2.md
  english/time-travel/0/3.md
  english/time-travel/0/4.md
  english/time-travel/1/0.md
  english/time-travel/1/1.md
  english/time-travel/1/2.md
  english/time-travel/begin-journey.md
  english/time-travel/decision_tree.excalidraw
  english/time-travel/decision_tree.png
  src/data/dungeon-info.json
  start-new-game.md
  static/images/time-travel.jpg
Labels: beginner, documentation, enhancement, hacktoberfest-accepted

#164 Added link to home page on rooms
  src/components/layout.jsx
  src/templates/blog-post.jsx
Labels: beginner, documentation, enhancement, good first issue, hacktoberfest-accepted
