Repository MakeContributions/markdown-dungeon, pull requests merged in 2021-01, with the labels that each got.

#121 More paths for dungeon
  english/normal-dungeon/9/3-A.md
  english/normal-dungeon/9/3-C.md
  english/normal-dungeon/9/5-A.md
  english/normal-dungeon/9/5-AB.md
  english/normal-dungeon/9/5-B.md
  english/normal-dungeon/9/5-C.md
  english/normal-dungeon/9/5-CA.md
  english/normal-dungeon/9/5-D.md
  english/normal-dungeon/9/5-DA.md
  english/normal-dungeon/9/6-A.md
  english/normal-dungeon/9/6-B.md
  english/normal-dungeon/9/6-C.md
Labels: beginner, documentation, enhancement, hacktoberfest-accepted

#131 doc(normal-dungeon): use correct under contruction
  english/normal-dungeon/9/6-A.md
  english/normal-dungeon/9/6-C.md
Labels: bug

#136 Add Decision Tree Reference in README
  README.md
  english/covid-19/3/3.md
Labels: documentation, enhancement

#137 Fix Dungeon Title in Start Game File
  start-new-game.md
Labels: enhancement
