Repository MakeContributions/markdown-dungeon, pull requests merged in 2021-04, with the labels that each got.

#144 Improve home page UI.
  src/components/card-grid.jsx
  src/components/hide-appbar.jsx
  src/pages/index.jsx
  src/utils/styles.js
Labels: enhancement

#146 Cellar option added to 2, cellar file created as 3-D
  english/normal-dungeon/9/2.md
  english/normal-dungeon/9/3-D.md
Labels: beginner, documentation, enhancement

#147 adding new dungeon room
  english/normal-dungeon/9/3-D.md
  english/normal-dungeon/9/3-DA.md
Labels: documentation, enhancement
